version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - trading-network

  trading-bot:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app
      - OLLAMA_BASE_URL=http://ollama:11434
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    networks:
      - trading-network
    command: sh -c "python rag/setup_pinecone.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

networks:
  trading-network:
    driver: bridge

volumes:
  ollama_data:
