version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8765:8765" # WebSocket port
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY}
      - ALPACA_ENDPOINT=${ALPACA_ENDPOINT:-https://paper-api.alpaca.markets}
      - ALPACA_STREAM_ENDPOINT=${ALPACA_STREAM_ENDPOINT:-wss://stream.data.alpaca.markets/v2/iex}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME:-robin-ai}
      - REDIS_URL=redis://redis:6379
      - OLLAMA_HOST=http://ollama:11434
      - MODEL_NAME=llama3
      - EMBEDDING_MODEL=nomic-embed-text
      - LOG_LEVEL=DEBUG
      - ENABLE_REAL_TIME=true
      - WS_HOST=0.0.0.0
      - WS_PORT=8765
      - PORT=8000
    volumes:
      - ./backend:/app
      - ./data/pdfs:/app/data/pdfs
      - model_cache:/app/model_cache
    restart: unless-stopped
    depends_on:
      ollama:
        condition: service_healthy
      redis:
        condition: service_healthy
      market_stream:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  market_stream:
    build:
      context: ./backend
      dockerfile: Dockerfile.stream
    ports:
      - "8001:8001" # Health check and API port
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY}
      - ALPACA_ENDPOINT=${ALPACA_ENDPOINT:-https://paper-api.alpaca.markets}
      - ALPACA_STREAM_ENDPOINT=${ALPACA_STREAM_ENDPOINT:-wss://stream.data.alpaca.markets/v2/iex}
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=INFO
      - PORT=8001
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./next.config.js:/app/next.config.js
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8765
      - NODE_ENV=development
    depends_on:
      - backend
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    entrypoint: [ "/bin/ollama" ]
    command: [ "serve" ]
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --save 60 1 --loglevel warning
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama_data:
  redis_data:
  model_cache:
